import { Mouse } from "@/components/mouse";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className}`}>
				<Mouse />
				<header className="fixed top-0 left-0 w-full z-50">
					<Link
						href="/"
						role="alert"
						className="w-full bg-yellow-400/20 backdrop-blur-lg animate-appearance-in border-yellow-400/20 border p-2 items-center justify-center text-center group inline-flex text-sm"
					>
						<span className="group-hover:underline">
							Build your OWN SaaS application!
						</span>{" "}
						<span className="w-3 ml-2">🤑</span>
						<span className="w-2 ml-1">💲</span>
						<span className="w-2">💲</span>
					</Link>
				</header>

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
